statement = { SOI ~ (assign | expr)? ~ EOI }

assign = { identifier ~ "=" ~ expr }

expr = { primary ~ (infix ~ primary)* }

infix = _{ add | sub | mul | div | pow }
add   =  { "+" }
sub   =  { "-" }
mul   =  { "*" }
div   =  { "/" }
pow   =  { "^" }

primary    = _{
    call
  | "(" ~ expr ~ ")"
  | symbol
  | number
}
symbol     =  { identifier }
number     =  { ASCII_DIGIT+ }
identifier =  { (ASCII_ALPHA | "_") ~ (ASCII_ALPHA | "_" | ASCII_DIGIT)* }
call       =  { identifier ~ "(" ~ (expr ~ ("," ~ expr)*)? ~ ")" }
